### ISSUE TITLE
Find templates or our shop

### ISSUE THREAD

**Issue by quyetdc** [quyetdc/2Q-Shop#1]

**Comment by ngocquyhoang** [comment]
Completed issues #1

**Comment by quyetdc** [comment]
[![LGTM](http://lgtm.in/p/UIAtQ1dWp)](http://lgtm.in/i/UIAtQ1dWp)

[:+1:](http://lgtm.in/u/UIAtQ1dWp) [:-1:](http://lgtm.in/r/UIAtQ1dWp)
