### ISSUE TITLE
Change the index page

### ISSUE THREAD

**Issue by quyetdc** [quyetdc/2Q-Shop#7]
- Change from "home/index" => products#index
- Show real data from our database after the issue #6

**Comment by ngocquyhoang** [comment]
Page "home" and page "product" have different. and I set root is home.
 And I don't using "product" for controller , I use "shop"

**Comment by quyetdc** [comment]
beside index action, how about action create, new, edit, update, destroy, search? which controller will we use? if we use ProductsController, it will like the Rails way. You can test by a rails generate scaffold (in another test app) to see :-)

**Comment by ngocquyhoang** [comment]
Yes ser :+1:
